/**
 * The music genre catalogue and the starter voices.
 *
 * Genres are rows so the picker can grow by request and a genre that comes
 * out wrong is fixed by editing `promptHints`, not by a release. The hints
 * are written for a music model: instruments, rhythm, production, vocal
 * delivery — never an artist's name, which the models refuse.
 *
 * Families group the picker: african · afro-diaspora · pop · urban ·
 * electronic · latin · asian · roots · mood. Sort puts West Africa first
 * because that is where the first customers are; nothing else is ranked.
 */

export interface GenreSeed {
  key: string;
  name: string;
  region: string;
  family: string;
  description: string;
  promptHints: string;
  bpm?: [number, number];
  languages: string[];
  sort: number;
}

const g = (
  key: string,
  name: string,
  region: string,
  family: string,
  description: string,
  promptHints: string,
  languages: string[],
  sort: number,
  bpm?: [number, number],
): GenreSeed => ({ key, name, region, family, description, promptHints, languages, sort, bpm });

export const GENRES: GenreSeed[] = [
  // ---- african -------------------------------------------------------------
  g(
    'afrobeats',
    'Afrobeats',
    'Nigeria · Ghana',
    'african',
    'The sound of Lagos and Accra: bouncy, warm, made for dancing.',
    'modern Afrobeats: log drum and shaker groove, syncopated percussion, warm sub bass, bright synth stabs, guitar licks, laid-back melodic vocals with pidgin ad-libs, polished pop production',
    ['en', 'pcm', 'yo', 'ig', 'tw'],
    1,
    [98, 112],
  ),
  g(
    'amapiano',
    'Amapiano',
    'South Africa',
    'african',
    'Deep, patient, piano-led house from the townships.',
    'Amapiano: log drum bassline, soft jazzy piano chords, shakers, spacious groove, airy pads, sparse vocals or chant hooks, long build-ups, deep house tempo',
    ['en', 'zu', 'xh'],
    2,
    [110, 118],
  ),
  g(
    'highlife',
    'Highlife',
    'Ghana · Nigeria',
    'african',
    'Guitars and horns, the sound of a good wedding.',
    'Highlife: interlocking clean electric guitars, brass section, congas and bell patterns, walking bass, joyful call-and-response vocals, live-band warmth',
    ['en', 'tw', 'ig'],
    3,
    [100, 125],
  ),
  g(
    'afro-gospel',
    'Afro-gospel',
    'Nigeria · Ghana',
    'african',
    'Praise you can dance to, for Sunday and for the shop.',
    'Afro-gospel praise: uplifting major-key progression, driving Afrobeats percussion, choir harmonies, soaring lead vocal, keys and horns, celebratory energy',
    ['en', 'yo', 'ig', 'tw'],
    4,
    [110, 130],
  ),
  g(
    'fuji',
    'Fuji',
    'Nigeria (Yoruba)',
    'african',
    'Talking drums and percussion, straight from the street party.',
    'Fuji: dense Yoruba percussion — talking drum, sakara, bata — call-and-response chanted vocals, minimal melody instruments, hypnotic groove, live and raw',
    ['yo'],
    5,
    [100, 120],
  ),
  g(
    'juju',
    'Jùjú',
    'Nigeria (Yoruba)',
    'african',
    'Guitar-driven Yoruba dance music with talking drums.',
    'Jùjú: layered clean guitars, talking drum, steel pedal guitar accents, gentle percussion, warm praise vocals in Yoruba, long flowing groove',
    ['yo', 'en'],
    6,
    [95, 115],
  ),
  g(
    'afro-rnb',
    'Afro-R&B',
    'Nigeria · UK',
    'african',
    'Smooth and late-night, Afrobeats slowed to a heartbeat.',
    'Afro-R&B: mid-tempo Afrobeats drums, lush chords, soft 808s, silky layered vocals with runs, moody and romantic production',
    ['en', 'pcm'],
    7,
    [85, 100],
  ),
  g(
    'bongo-flava',
    'Bongo Flava',
    'Tanzania',
    'african',
    'Swahili pop with heart.',
    'Bongo Flava: East African pop, melodic Swahili vocals, gentle Afro-pop drums, sweet guitar lines, romantic and radio-ready',
    ['sw', 'en'],
    8,
    [95, 110],
  ),
  g(
    'gengetone',
    'Gengetone',
    'Kenya',
    'african',
    'Nairobi street rap over club beats.',
    'Gengetone: hard dancehall-influenced beat, chanted Sheng rap vocals, big hooks, club energy',
    ['sw', 'en'],
    9,
    [95, 105],
  ),
  g(
    'gqom',
    'Gqom',
    'South Africa (Durban)',
    'african',
    'Dark, minimal, pounding club music.',
    'Gqom: raw broken-beat kick pattern, dark minimal synths, chants, heavy sub, sparse and hypnotic',
    ['zu', 'en'],
    10,
    [120, 130],
  ),
  g(
    'kwaito',
    'Kwaito',
    'South Africa',
    'african',
    'Slowed house with township swagger.',
    'Kwaito: slowed house beat, deep bass, chanted vocals, catchy repeated hooks, laid-back groove',
    ['zu', 'en'],
    11,
    [100, 115],
  ),
  g(
    'soukous',
    'Soukous',
    'DR Congo',
    'african',
    'Fast, sparkling guitar music from Kinshasa.',
    'Soukous: fast interlocking clean guitars, sebene guitar breaks, driving snare and hi-hat, bright horns, joyful Lingala vocals',
    ['ln', 'fr'],
    12,
    [125, 145],
  ),
  g(
    'coupe-decale',
    'Coupé-Décalé',
    'Côte d’Ivoire',
    'african',
    'Ivorian party music with a bounce.',
    'Coupé-Décalé: bouncy electronic drums, tight percussion, shout-along hooks, playful French vocals, club atmosphere',
    ['fr'],
    13,
    [120, 130],
  ),
  g(
    'mbalax',
    'Mbalax',
    'Senegal',
    'african',
    'Sabar drums at the centre of everything.',
    'Mbalax: rapid sabar and tama drum patterns, bright keyboard stabs, syncopated bass, powerful Wolof vocals',
    ['wo', 'fr'],
    14,
    [120, 140],
  ),
  g(
    'afro-house',
    'Afro House',
    'South Africa · global',
    'african',
    'Deep house with African percussion.',
    'Afro house: four-on-the-floor kick, layered organic percussion, deep warm bass, soulful vocal chops, spiritual atmosphere',
    ['en'],
    15,
    [118, 125],
  ),
  g(
    'ethio-jazz',
    'Ethio-jazz',
    'Ethiopia',
    'african',
    'Pentatonic horns over a slow groove.',
    'Ethio-jazz: Ethiopian pentatonic scales, brass and saxophone leads, vibraphone, slow funky groove, smoky atmosphere',
    ['am', 'en'],
    16,
    [80, 100],
  ),
  g(
    'rai',
    'Raï',
    'Algeria',
    'african',
    'North African pop with a rebel streak.',
    'Raï: Maghrebi pop, synth accordion and strings, driving derbouka percussion, melismatic Arabic vocals',
    ['ar', 'fr'],
    17,
    [100, 120],
  ),
  g(
    'arabic-pop',
    'Arabic pop',
    'Egypt · Gulf · Levant',
    'african',
    'Modern Arabic pop with strings and percussion.',
    'Arabic pop: modern production with oud and string section, darbuka and riq percussion, maqam-flavoured melody, expressive Arabic vocals',
    ['ar'],
    18,
    [95, 120],
  ),
  // ---- afro-diaspora --------------------------------------------------------
  g(
    'dancehall',
    'Dancehall',
    'Jamaica',
    'afro-diaspora',
    'Riddim-driven and built for the dance.',
    'Dancehall: digital riddim, syncopated kick and snare, deep bass, patois-flavoured toasting vocals, big call-out hooks',
    ['en'],
    20,
    [90, 105],
  ),
  g(
    'reggae',
    'Reggae',
    'Jamaica',
    'afro-diaspora',
    'One-drop rhythm, roots and message.',
    'Roots reggae: one-drop drum pattern, offbeat skank guitar and organ, heavy melodic bass, relaxed soulful vocals',
    ['en'],
    21,
    [70, 90],
  ),
  g(
    'afroswing',
    'Afroswing',
    'UK',
    'afro-diaspora',
    'London’s blend of Afrobeats, dancehall and rap.',
    'Afroswing: UK production, bouncy Afrobeats-dancehall drums, melodic rap-sung vocals, moody synths',
    ['en'],
    22,
    [95, 110],
  ),
  g(
    'zouk',
    'Zouk / Kizomba',
    'Antilles · Angola',
    'afro-diaspora',
    'Slow, sensual, close-dance music.',
    'Kizomba / zouk: slow sensual groove, soft electronic drums, romantic guitar and keys, smooth vocals in Portuguese or French',
    ['pt', 'fr'],
    23,
    [85, 100],
  ),
  g(
    'reggaeton',
    'Reggaetón',
    'Puerto Rico · global',
    'afro-diaspora',
    'The dembow beat that runs the world’s clubs.',
    'Reggaetón: dembow rhythm, heavy 808 bass, minor-key synth melody, confident Spanish vocals, club-ready',
    ['es'],
    24,
    [88, 100],
  ),
  // ---- pop ------------------------------------------------------------------
  g(
    'pop',
    'Pop',
    'Global',
    'pop',
    'Big hooks, clean production, radio-ready.',
    'contemporary pop: punchy drums, layered synths and piano, big anthemic chorus, polished stacked vocals',
    ['en'],
    30,
    [100, 125],
  ),
  g(
    'dance-pop',
    'Dance pop',
    'Global',
    'pop',
    'Pop with a four-on-the-floor pulse.',
    'dance pop: four-on-the-floor kick, sidechained synth chords, bright plucks, euphoric chorus, energetic vocals',
    ['en'],
    31,
    [118, 128],
  ),
  g(
    'indie-pop',
    'Indie pop',
    'Global',
    'pop',
    'Softer, quirkier, a little dreamy.',
    'indie pop: jangly guitars, soft synths, light drums, intimate breathy vocals, wistful mood',
    ['en'],
    32,
    [95, 120],
  ),
  g(
    'k-pop',
    'K-pop',
    'South Korea',
    'pop',
    'High-energy, genre-hopping, immaculate.',
    'K-pop: high-energy production, switching sections between EDM drops, trap verses and pop chorus, layered group vocals, Korean and English lyrics',
    ['ko', 'en'],
    33,
    [110, 130],
  ),
  g(
    'j-pop',
    'J-pop',
    'Japan',
    'pop',
    'Bright, melodic, full of chord changes.',
    'J-pop: bright melodic production, rich chord changes, energetic drums, clean guitars and synths, expressive Japanese vocals',
    ['ja'],
    34,
    [120, 140],
  ),
  g(
    'bollywood',
    'Bollywood',
    'India',
    'pop',
    'Film-song drama: strings, dhol and a big chorus.',
    'Bollywood film song: lush string section, dhol and tabla percussion, sitar accents, modern pop drums, soaring Hindi vocals',
    ['hi'],
    35,
    [90, 120],
  ),
  g(
    'bhangra',
    'Bhangra',
    'Punjab',
    'pop',
    'Dhol-driven celebration music.',
    'Bhangra: pounding dhol, tumbi riff, energetic Punjabi vocals, modern club production',
    ['pa', 'en'],
    36,
    [120, 140],
  ),
  g(
    'mandopop',
    'Mandopop',
    'China · Taiwan',
    'pop',
    'Melodic Mandarin ballads and pop.',
    'Mandopop: melodic piano-led production, gentle drums, string swells, emotional Mandarin vocals',
    ['zh'],
    37,
    [70, 110],
  ),
  g(
    'v-pop',
    'V-pop',
    'Vietnam',
    'pop',
    'Vietnamese pop, sweet and modern.',
    'V-pop: modern pop production, soft synths, catchy chorus, clear Vietnamese vocals',
    ['vi'],
    38,
    [95, 125],
  ),
  g(
    'turkish-pop',
    'Turkish pop',
    'Türkiye',
    'pop',
    'Pop with a Mediterranean pulse.',
    'Turkish pop: darbuka and clap rhythm, baglama accents, string section, modern synth pop production, expressive Turkish vocals',
    ['tr'],
    39,
    [100, 125],
  ),
  // ---- urban ---------------------------------------------------------------
  g(
    'hip-hop',
    'Hip-hop',
    'USA · global',
    'urban',
    'Boom-bap to modern: beats and bars.',
    'hip-hop: hard drums, sampled or synth melody, deep bass, confident rap vocals with a hook',
    ['en'],
    40,
    [85, 100],
  ),
  g(
    'trap',
    'Trap',
    'USA · global',
    'urban',
    'Rolling hi-hats and 808s.',
    'trap: rolling triplet hi-hats, booming 808 bass, dark synth melody, melodic rap vocals with ad-libs',
    ['en'],
    41,
    [130, 150],
  ),
  g(
    'drill',
    'Drill',
    'UK · USA · Ghana',
    'urban',
    'Sliding 808s and cold energy.',
    'drill: sliding 808 bass, sparse dark piano, skippy hi-hats, aggressive rhythmic rap vocals',
    ['en'],
    42,
    [138, 146],
  ),
  g(
    'rnb',
    'R&B',
    'USA · global',
    'urban',
    'Smooth, soulful, late night.',
    'contemporary R&B: smooth chords, soft drums, deep bass, silky layered vocals with runs and harmonies',
    ['en'],
    43,
    [70, 95],
  ),
  g(
    'neo-soul',
    'Neo-soul',
    'USA · UK',
    'urban',
    'Live-feel soul with jazzy chords.',
    'neo-soul: Rhodes keys, jazzy chord voicings, laid-back live drums, warm bass, soulful intimate vocals',
    ['en'],
    44,
    [70, 95],
  ),
  g(
    'grime',
    'Grime',
    'UK',
    'urban',
    'Fast, sharp, London.',
    'grime: 140 BPM, square-wave bass, sharp syncopated drums, rapid-fire rap vocals',
    ['en'],
    45,
    [138, 142],
  ),
  // ---- electronic ----------------------------------------------------------
  g(
    'house',
    'House',
    'Chicago · global',
    'electronic',
    'Four to the floor, all night.',
    'house: four-on-the-floor kick, off-beat hi-hats, piano stabs, filtered disco samples, soulful vocal hook',
    ['en'],
    50,
    [120, 126],
  ),
  g(
    'techno',
    'Techno',
    'Detroit · Berlin',
    'electronic',
    'Dark, driving, hypnotic.',
    'techno: driving kick, industrial percussion, dark hypnotic synth sequences, minimal or no vocals',
    ['en'],
    51,
    [125, 135],
  ),
  g(
    'edm',
    'EDM / big room',
    'Global',
    'electronic',
    'Festival drops and hands in the air.',
    'EDM: euphoric build-ups, big synth lead drop, sidechained chords, festival energy, anthemic vocal hook',
    ['en'],
    52,
    [126, 130],
  ),
  g(
    'drum-and-bass',
    'Drum and bass',
    'UK',
    'electronic',
    'Fast breakbeats and deep bass.',
    'drum and bass: fast breakbeat drums, deep rolling bass, atmospheric pads, occasional vocal hook',
    ['en'],
    53,
    [170, 176],
  ),
  g(
    'lofi',
    'Lo-fi beats',
    'Global',
    'electronic',
    'Dusty, calm, for working and scrolling.',
    'lo-fi hip-hop: dusty drums, vinyl crackle, mellow jazzy keys, soft bass, instrumental, relaxed',
    ['en'],
    54,
    [70, 90],
  ),
  g(
    'synthwave',
    'Synthwave',
    'Global',
    'electronic',
    'Neon eighties nostalgia.',
    'synthwave: retro analog synths, gated reverb drums, arpeggios, nostalgic eighties atmosphere',
    ['en'],
    55,
    [85, 110],
  ),
  // ---- latin ---------------------------------------------------------------
  g(
    'latin-pop',
    'Latin pop',
    'Latin America · Spain',
    'latin',
    'Warm, rhythmic, sung in Spanish.',
    'Latin pop: warm rhythmic production, nylon guitar, light percussion, catchy chorus, Spanish vocals',
    ['es'],
    60,
    [95, 120],
  ),
  g(
    'cumbia',
    'Cumbia',
    'Colombia · Mexico',
    'latin',
    'The rhythm everyone can dance to.',
    'cumbia: guacharaca and güiro rhythm, accordion or synth accordion, bass tumbao, festive brass, Spanish vocals',
    ['es'],
    61,
    [90, 105],
  ),
  g(
    'bachata',
    'Bachata',
    'Dominican Republic',
    'latin',
    'Romantic guitar and heartbreak.',
    'bachata: requinto guitar lead, bongo and güira, romantic melody, heartfelt Spanish vocals',
    ['es'],
    62,
    [120, 135],
  ),
  g(
    'salsa',
    'Salsa',
    'Cuba · Puerto Rico · NY',
    'latin',
    'Horns, montuno and clave.',
    'salsa: piano montuno, clave, congas and timbales, brass section, powerful call-and-response Spanish vocals',
    ['es'],
    63,
    [160, 200],
  ),
  g(
    'samba',
    'Samba / pagode',
    'Brazil',
    'latin',
    'Brazilian joy, cavaquinho and surdo.',
    'samba pagode: cavaquinho, pandeiro and surdo, tantan, joyful Portuguese vocals, carnival energy',
    ['pt'],
    64,
    [95, 110],
  ),
  g(
    'bossa-nova',
    'Bossa nova',
    'Brazil',
    'latin',
    'Soft, sophisticated, seaside.',
    'bossa nova: nylon guitar syncopation, soft brushed drums, jazzy chords, gentle intimate Portuguese vocals',
    ['pt', 'en'],
    65,
    [120, 140],
  ),
  g(
    'funk-carioca',
    'Funk carioca',
    'Brazil (Rio)',
    'latin',
    'Baile funk: raw, fast, loud.',
    'funk carioca: tamborzão beat, heavy bass, chopped vocal samples, energetic Portuguese vocals',
    ['pt'],
    66,
    [125, 135],
  ),
  g(
    'regional-mexicano',
    'Regional Mexicano',
    'Mexico',
    'latin',
    'Corridos, banda and norteño.',
    'regional Mexican: requinto and acoustic guitars, tuba or bajo sexto bass, accordion, brass banda accents, storytelling Spanish vocals',
    ['es'],
    67,
    [90, 130],
  ),
  // ---- roots ---------------------------------------------------------------
  g(
    'gospel',
    'Gospel',
    'USA',
    'roots',
    'Choir, organ and joy.',
    'gospel: Hammond organ, piano, full choir harmonies, hand claps, building energy, powerful lead vocal',
    ['en'],
    70,
    [70, 120],
  ),
  g(
    'soul-funk',
    'Soul / funk',
    'USA',
    'roots',
    'Groove, horns and heart.',
    'soul funk: tight drum groove, slap bass, horn stabs, wah guitar, warm powerful vocals',
    ['en'],
    71,
    [95, 115],
  ),
  g(
    'jazz',
    'Jazz',
    'Global',
    'roots',
    'Swing, improvisation, elegance.',
    'jazz: swing drums, walking upright bass, piano comping, saxophone or trumpet lead, mostly instrumental',
    ['en'],
    72,
    [80, 160],
  ),
  g(
    'blues',
    'Blues',
    'USA',
    'roots',
    'Twelve bars of truth.',
    'blues: twelve-bar progression, electric guitar licks, shuffle drums, harmonica, raw expressive vocals',
    ['en'],
    73,
    [70, 110],
  ),
  g(
    'country',
    'Country',
    'USA',
    'roots',
    'Stories, guitars, open road.',
    'country: acoustic and pedal steel guitars, steady drums, fiddle accents, storytelling vocals',
    ['en'],
    74,
    [90, 130],
  ),
  g(
    'rock',
    'Rock',
    'Global',
    'roots',
    'Guitars, drums, volume.',
    'rock: distorted electric guitars, driving drums, bass, anthemic chorus, powerful vocals',
    ['en'],
    75,
    [110, 150],
  ),
  g(
    'acoustic-folk',
    'Acoustic folk',
    'Global',
    'roots',
    'One voice, one guitar.',
    'acoustic folk: fingerpicked acoustic guitar, light percussion, intimate honest vocals, warm and simple',
    ['en'],
    76,
    [80, 120],
  ),
  g(
    'flamenco',
    'Flamenco pop',
    'Spain',
    'roots',
    'Palmas, guitar and fire.',
    'flamenco pop: flamenco guitar, palmas hand claps, cajón, passionate Spanish vocals, modern pop touches',
    ['es'],
    77,
    [100, 130],
  ),
  g(
    'celtic',
    'Celtic',
    'Ireland · Scotland',
    'roots',
    'Fiddles, whistles and stomp.',
    'Celtic folk: fiddle, tin whistle, bodhrán, acoustic guitar, lively jig rhythm or gentle air',
    ['en'],
    78,
    [90, 140],
  ),
  g(
    'classical',
    'Classical / orchestral',
    'Global',
    'roots',
    'Strings and grandeur.',
    'orchestral: full string section, woodwinds, brass, timpani, cinematic classical arrangement, instrumental',
    ['en'],
    79,
    [60, 140],
  ),
  // ---- mood (mostly instrumental beds for ads and reels) --------------------
  g(
    'cinematic',
    'Cinematic',
    'Global',
    'mood',
    'Trailer-sized emotion for a product reveal.',
    'cinematic score: swelling strings, deep braams, epic percussion, building tension and release, instrumental',
    ['en'],
    80,
    [70, 120],
  ),
  g(
    'corporate-upbeat',
    'Upbeat advert',
    'Global',
    'mood',
    'Bright, clappy, positive — the ad bed.',
    'upbeat advertising bed: bright acoustic guitar, claps, glockenspiel, light drums, optimistic and clean, instrumental',
    ['en'],
    81,
    [110, 128],
  ),
  g(
    'chill-ambient',
    'Chill / ambient',
    'Global',
    'mood',
    'Soft pads for a calm reel.',
    'ambient chill: soft evolving pads, gentle piano, subtle percussion, spacious and calm, instrumental',
    ['en'],
    82,
    [60, 90],
  ),
  g(
    'kids',
    'Children’s',
    'Global',
    'mood',
    'Playful and simple, for the little ones.',
    'children’s song: playful ukulele and xylophone, simple bouncy rhythm, cheerful sing-along vocals, clean and sweet',
    ['en'],
    83,
    [100, 130],
  ),
  g(
    'wedding',
    'Wedding',
    'Global',
    'mood',
    'Romantic and grand, for the big day.',
    'romantic wedding song: piano and strings, gentle drums, heartfelt vocals, building to a grand chorus',
    ['en'],
    84,
    [65, 95],
  ),
  g(
    'birthday',
    'Birthday',
    'Global',
    'mood',
    'A song with their name in it.',
    'celebratory birthday song: bright pop production, party drums, claps and horns, joyful sing-along vocals that name the person',
    ['en'],
    85,
    [110, 130],
  ),
];

/**
 * Starter voices. ElevenLabs premade voice ids are the vendor's public
 * library; Google and OpenAI voices are named by the vendor. Add African
 * English voices from ElevenLabs' community library as rows once the
 * account is on a plan that permits them.
 */
export interface VoiceSeed {
  key: string;
  providerKey: string;
  providerVoiceId: string;
  name: string;
  language: string;
  accent?: string;
  gender?: string;
  tags: string[];
  sort: number;
}
const v = (
  key: string,
  providerKey: string,
  providerVoiceId: string,
  name: string,
  language: string,
  accent: string | undefined,
  gender: string | undefined,
  tags: string[],
  sort: number,
): VoiceSeed => ({ key, providerKey, providerVoiceId, name, language, accent, gender, tags, sort });

export const VOICES: VoiceSeed[] = [
  v('el-rachel', 'elevenlabs:tts', '21m00Tcm4TlvDq8ikWAM', 'Rachel', 'en', 'American', 'female', ['calm', 'narration'], 10),
  v('el-adam', 'elevenlabs:tts', 'pNInz6obpnDQGcFmaJgB', 'Adam', 'en', 'American', 'male', ['deep', 'narration', 'ad'], 11),
  v('el-bella', 'elevenlabs:tts', 'EXAVITQu4vr4xnSDxMaL', 'Bella', 'en', 'American', 'female', ['soft', 'friendly'], 12),
  v('el-antoni', 'elevenlabs:tts', 'ErXwobaYiN019PkySvjV', 'Antoni', 'en', 'American', 'male', ['warm', 'conversational'], 13),
  v('el-domi', 'elevenlabs:tts', 'AZnzlk1XvdvUeBnXmlld', 'Domi', 'en', 'American', 'female', ['energetic', 'ad'], 14),
  v('el-josh', 'elevenlabs:tts', 'TxGEqnHWrfWFTfGW9XjX', 'Josh', 'en', 'American', 'male', ['young', 'energetic'], 15),
  v('g-ng-a', 'google:tts', 'en-NG-Standard-A', 'Adaeze', 'en-NG', 'Nigerian', 'female', ['clear', 'announcer'], 20),
  v('g-ng-b', 'google:tts', 'en-NG-Standard-B', 'Emeka', 'en-NG', 'Nigerian', 'male', ['clear', 'announcer'], 21),
  v('g-ng-c', 'google:tts', 'en-NG-Standard-C', 'Funmi', 'en-NG', 'Nigerian', 'female', ['warm'], 22),
  v('g-ng-d', 'google:tts', 'en-NG-Standard-D', 'Tunde', 'en-NG', 'Nigerian', 'male', ['warm'], 23),
  v('g-ke-a', 'google:tts', 'en-KE-Standard-A', 'Wanjiru', 'en-KE', 'Kenyan', 'female', ['clear'], 24),
  v('g-ke-b', 'google:tts', 'en-KE-Standard-B', 'Otieno', 'en-KE', 'Kenyan', 'male', ['clear'], 25),
  v('g-za-a', 'google:tts', 'en-ZA-Standard-A', 'Naledi', 'en-ZA', 'South African', 'female', ['clear'], 26),
  v('g-fr-a', 'google:tts', 'fr-FR-Standard-A', 'Camille', 'fr', 'French', 'female', ['clear'], 27),
  v('g-pt-br-a', 'google:tts', 'pt-BR-Standard-A', 'Ana', 'pt-BR', 'Brazilian', 'female', ['clear'], 28),
  v('oa-nova', 'openai:tts', 'nova', 'Nova', 'en', 'American', 'female', ['friendly', 'fast'], 30),
  v('oa-onyx', 'openai:tts', 'onyx', 'Onyx', 'en', 'American', 'male', ['deep', 'fast'], 31),
  v('oa-coral', 'openai:tts', 'coral', 'Coral', 'en', 'American', 'female', ['warm', 'fast'], 32),
];
