// One ESLint config for the whole monorepo. Each package runs
// `eslint . --max-warnings 0` from its own directory and picks this up.
//
// Deliberately not type-aware: type-aware rules re-typecheck every file and
// make lint the slowest job in CI for little gain — `tsc --noEmit` already
// runs. What lint is for here is the class of mistake the compiler accepts
// and a reviewer misses: an unused import, a floating `any`, a `let` that
// never changes.
import js from '@eslint/js';
import tseslint from 'typescript-eslint';
import globals from 'globals';
import prettier from 'eslint-config-prettier';

export default tseslint.config(
  {
    ignores: [
      '**/node_modules/**',
      '**/dist/**',
      '**/.next/**',
      '**/.open-next/**',
      '**/.turbo/**',
      '**/coverage/**',
      '**/*.d.ts',
      'apps/web/next-env.d.ts',
      'apps/web/content/**', // generated by scripts/sync-prototypes.mjs
      'apps/web/open-next.config.ts',
    ],
  },
  js.configs.recommended,
  ...tseslint.configs.recommended,
  // Formatting is Prettier's job (see .prettierrc and the pre-commit hook);
  // this switches off every ESLint rule that would argue with it.
  prettier,
  {
    languageOptions: {
      globals: { ...globals.node, ...globals.browser },
    },
    rules: {
      // Nest's DI relies on constructor parameters that exist only for their
      // type, and decorators reference classes before they are "used".
      '@typescript-eslint/no-unused-vars': ['error', { argsIgnorePattern: '^_', varsIgnorePattern: '^_', caughtErrors: 'none' }],
      // Prisma and Express types leak `any` at their edges; refusing it
      // outright would mean casts everywhere, which hide more than they show.
      '@typescript-eslint/no-explicit-any': 'warn',
      '@typescript-eslint/no-empty-object-type': 'off',
      'no-console': ['error', { allow: ['warn', 'error'] }],
      'prefer-const': 'error',
      eqeqeq: ['error', 'smart'],
    },
  },
  {
    // Scripts and seeds print on purpose, and the worker has no logger yet:
    // its structured console lines are its log until the pipeline lands.
    files: ['scripts/**', 'packages/db/prisma/seed.ts', 'apps/worker/src/**', '**/*.spec.ts', '**/*.test.ts'],
    rules: { 'no-console': 'off' },
  },
);
